<a href="https://colab.research.google.com/github/akshayambavane/Machine-Learning-in-90-days/blob/master/NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Import numpy library  

In [ ]:
import numpy as np

### Create an Array using array function  

In [ ]:
arr = np.array([1, 2, 3])

### Create an Array containing numbers from 20 to 40 

In [ ]:
a = np.arange(20, 41)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

### Create an array which contain 10 elements and every element is 5  

In [ ]:
b = np.ones(10)*5
b

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

### create a 1-d array and then convert it into 3-d array  

In [ ]:
c = np.arange(1, 25)
c = c.reshape(2, 3, 4)
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### Create 2-d array which contains random 25 numbers between 0 and 1 

In [ ]:
d = np.random.rand(5, 5)
d

array([[ 0.44025718,  0.08372648,  0.71233018,  0.42786349,  0.2977805 ],
       [ 0.49208478,  0.74029639,  0.35772892,  0.41720995,  0.65472131],
       [ 0.37380143,  0.23451288,  0.98799529,  0.76599595,  0.77700444],
       [ 0.02798196,  0.17390652,  0.15408224,  0.07708648,  0.8898657 ],
       [ 0.7503787 ,  0.69340324,  0.51176338,  0.46426806,  0.56843069]])

### create array containing 20 random integer then replace every even number with -1 
#### Example - 
####                  array --- >  [44,55,12,6,3] 
####                  ouput ----> [-1,55, -1,-1,3]


In [ ]:
np.random.seed(123)
e = np.random.randint(1, 50, 20)
e[e % 2 == 0] = -1
e

array([-1,  3, 29, 35, 39, -1, -1, 43, 23, -1, 33, -1, -1, 33, 47, 33, -1,
       -1, -1, 15])

#### You have a matrix 
[[5 , 10, 15, 20, 25],
[30, 35, 40, 45, 50],
[55, 60, 65, 70, 75],
[80, 85, 90, 95, 100]]

Extract
[30,35,40]
[55, 60, 65]

In [ ]:
f = np.array([[5 , 10, 15, 20, 25], [30, 35, 40, 45, 50], [55, 60, 65, 70, 75], [80, 85, 90, 95, 100]])
f = f[1:3, 0:3]
f

array([[30, 35, 40],
       [55, 60, 65]])

### Concatenate two 1-d array   

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arrr = np.hstack((arr1, arr2)) # add tuple in perenthases 
arrr

array([1, 2, 3, 4, 5, 6])

### Stack 2-d matrix horizontally and vertically

In [ ]:
np.random.seed(123)
matrix1 = np.random.randint(1, 10, 9).reshape(3, 3)
matrix2 = np.random.randint(11, 20, 9).reshape(3, 3)
matrix1

array([[3, 3, 7],
       [2, 4, 7],
       [2, 1, 2]])

In [ ]:
matrix2

array([[11, 11, 14],
       [15, 11, 11],
       [15, 12, 18]])

In [ ]:
np.hstack((matrix1, matrix2))

array([[ 3,  3,  7, 11, 11, 14],
       [ 2,  4,  7, 15, 11, 11],
       [ 2,  1,  2, 15, 12, 18]])

In [ ]:
np.vstack((matrix1, matrix2))

array([[ 3,  3,  7],
       [ 2,  4,  7],
       [ 2,  1,  2],
       [11, 11, 14],
       [15, 11, 11],
       [15, 12, 18]])

In [ ]:
np.concatenate((matrix1, matrix2))

array([[ 3,  3,  7],
       [ 2,  4,  7],
       [ 2,  1,  2],
       [11, 11, 14],
       [15, 11, 11],
       [15, 12, 18]])

### Convert array to float

In [ ]:
g = np.array([1,2,3,4,5, 6])
g.astype(float)

array([ 1.,  2.,  3.,  4.,  5.,  6.])

In [ ]:
matrix1.shape # gives no. rows and columns of array

(3, 3)

In [ ]:
g.shape

(6,)

In [ ]:
g.shape = (3, 2) # change shape of array
g

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
h = np.reshape(g, (2, 3))
h

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.transpose(h) # row = column & column = row

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
h.flatten() # convert to 1d array

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
np.concatenate((arr1, arr2, arr3))


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array_1 = np.array([[1,2,3],[0,0,0]])
array_2 = np.array([[0,0,0],[7,8,9]])
np.concatenate((array_1, array_2)) # or axis = 0

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0],
       [7, 8, 9]])

In [ ]:
np.concatenate((array_1, array_2), axis = 1)

array([[1, 2, 3, 0, 0, 0],
       [0, 0, 0, 7, 8, 9]])

In [ ]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [ ]:
np.zeros((2, 5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [ ]:
np.zeros((2,2,3)) # all same for ones

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])

In [ ]:
np.identity(3) #3 is for  dimension 3 X 3

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [ ]:
np.eye(3, 4, k = 1) # k = position, k = positive value is for coloumn & negative value for rows

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [ ]:
np.eye(3, 4, k = 0)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [ ]:
np.eye(7, 8, k = -3) # negative value for rows

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.]])

In [ ]:
np.eye(3, 3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [ ]:
a = np.array([1,2,3,4], float)
b = np.array([5,6,7,8], float)
a + b # same for -, *, /, %, **

array([  6.,   8.,  10.,  12.])

In [ ]:
np.add(a, b) # same for subtract, multiply, divide, mod, power

array([  6.,   8.,  10.,  12.])

In [ ]:
my_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
np.floor(my_array) # floor for get previous no.

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [ ]:
my_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
np.ceil(my_array) # floor for get next no.

array([  2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [ ]:
#The rint tool rounds to the nearest integer of input element-wise.
my_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
np.rint(my_array)

array([  1.,   2.,   3.,   4.,   6.,   7.,   8.,   9.,  10.])

In [ ]:
np.set_printoptions(sign=' ') # give extra one white space on print

### Sum & Product

In [ ]:
a = np.array([ [1, 2], [3, 4] ])
np.sum(a, axis = 0) # row wise

array([4, 6])

In [ ]:
np.sum(a, axis = 1) # column wise

array([3, 7])

In [ ]:
np.sum(a, axis = None)

10

In [ ]:
np.sum(a)

10

In [ ]:
np.prod(a, axis = 0)

array([3, 8])

In [ ]:
np.prod(a, axis = 1)

array([ 2, 12])

In [ ]:
np.prod(a, axis = None)

24

In [ ]:
np.prod(a)

24

### min & max

In [ ]:
b = np.array([[2, 5], 
              [3, 7],
              [1, 3],     
              [4, 0]])
b

array([[2, 5],
       [3, 7],
       [1, 3],
       [4, 0]])

In [ ]:
np.min(a, axis = 0)

array([1, 2])

In [ ]:
np.min(a, axis = 1)

array([1, 3])

In [ ]:
np.min(a, axis = None)

1

In [ ]:
np.min(a)

1

In [ ]:
np.max(a, axis = 0)

array([3, 4])

In [ ]:
np.max(a, axis = 1)

array([2, 4])

In [ ]:
np.max(a, axis = None)

4

In [ ]:
np.max(a)

4

### Mean, Variance & Standard variation

In [ ]:
c = np.array([ [1, 2], [3, 4] ])
c

array([[1, 2],
       [3, 4]])

In [ ]:
np.mean(c, axis = 0)

array([ 2.,  3.])

In [ ]:
np.mean(c, axis = 1)

array([ 1.5,  3.5])

In [ ]:
np.mean(c, axis = None)

2.5

In [ ]:
np.mean(c)

2.5

In [ ]:
np.var(c, axis = 0)

array([ 1.,  1.])

In [ ]:
np.var(c, axis = 1)

array([ 0.25,  0.25])

In [ ]:
np.var(c, axis = None)

1.25

In [ ]:
np.var(c)

1.25

In [ ]:
np.std(c, axis = 0)

array([ 1.,  1.])

In [ ]:
np.std(c, axis = 1)

array([ 0.5,  0.5])

In [ ]:
np.std(c, axis = None)

1.118033988749895

In [ ]:
np.std(c)

1.118033988749895

### Dot and Cross

In [ ]:
a = np.array([ 1, 2 ])
b = np.array([ 3, 4 ])

In [ ]:
np.dot(a, b)

11

In [ ]:
np.cross(a,b)

array(-2)

###Inner and Outer

In [ ]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])

In [ ]:
np.inner(a, b) # 0*3 + 1*4 + 2*5

14

In [ ]:
np.outer(a, b) # [0*3, 0*4, 0*5] [1*3, 1*4, 1*5] [2*3, 2*4, 2*5]

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [ 6,  8, 10]])

###Polynomials

In [ ]:
np.poly([-1, 1, 1, 10]) # poly

array([  1., -11.,   9.,  11., -10.])

In [ ]:
np.roots([1, 0, -1]) # roots

array([-1.,  1.])

In [ ]:
np.polyint([1, 1, 1])

array([ 0.33333333,  0.5       ,  1.        ,  0.        ])

In [ ]:
np.polyder([1, 1, 1, 1])

array([3, 2, 1])

In [ ]:
np.polyval([1, -2, 0, 2], 4)

34

In [ ]:
np.polyfit([0,1,-1, 2, -2], [0,1,1, 4, 4], 2)

array([ 1.00000000e+00,  0.00000000e+00, -3.17305762e-16])

##Linear Algebra

In [ ]:
np.linalg.det([[1 , 2], [2, 1]]) #determinant

-2.9999999999999996

In [ ]:
vals, vecs = np.linalg.eig([[1 , 2], [2, 1]]) #eigenvalues and right eigenvectors of a square array
vals

array([ 3., -1.])

In [ ]:
vecs

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [ ]:
np.linalg.inv([[1 , 2], [2, 1]]) #(multiplicative) inverse of a matrix.

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])